In [1]:
pip install -U pytest

Note: you may need to restart the kernel to use updated packages.


'C:\Program' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
# content of test_sample.py
def func(x):
    return x + 1


def test_answer():
    assert func(3) == 5

In [4]:
!pytest test_answer

============================= test session starts =============================
platform win32 -- Python 3.8.3, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: c:\KT\test.py\pytest_test_tut
plugins: cov-2.10.1
collected 0 items

============================== warnings summary ===============================
..\..\..\Program Files\Anaconda\lib\site-packages\pyreadline\py3k_compat.py:8
  C:\Program Files\Anaconda\lib\site-packages\pyreadline\py3k_compat.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    return isinstance(x, collections.Callable)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 warning in 0.06s ==============================


ERROR: file or directory not found: test_answer



In [1]:
string_ig="ig_aal-h10-b9702u1-cam001-20220327-06091546.jpg"
string_ig.replace("ig", "ed")

'ed_aal-h10-b9702u1-cam001-20220327-06091546.jpg'

In [2]:
filename="ig_aal-h10-b9702u1-cam001-20220327-06091546.jpg"
filename.split('.')[0]

'ig_aal-h10-b9702u1-cam001-20220327-06091546'

In [ ]:
"(){[]}()"
"(){}[]"
"({]})"

In [6]:
string_value = "(){[]}()"
string_value = "({]})"

def cal_brackets(str_value):
    dic_bracket ={
        "(" : 0,
         ")": 0,
         "[": 0,
         "]": 0,
        "{" : 0,
        "}":  0
    }
    count_round = 0
    count_square = 0
    count_curl = 0
    for k,v in dic_bracket.items():
        if k in str_value:
            dic_bracket[k]+=1
    print(dic_bracket)        
    
cal_brackets(string_value) 

{'(': 1, ')': 1, '[': 0, ']': 1, '{': 1, '}': 1}


In [7]:
Array1= [1,7,0,0,8,0,10,12,0,4]
for i in sorted(Array1):
    if i ==0:
        Array1.append(i)
        Array1.remove(i)
print(Array1)

[1, 7, 8, 10, 12, 4, 0, 0, 0, 0]


In [10]:
import numpy as np

rand_arr = np.random.randint(1,9, 100)

rand_arr

array([8, 7, 6, 8, 3, 3, 2, 3, 8, 2, 3, 1, 2, 2, 4, 1, 8, 8, 4, 3, 2, 1,
       3, 4, 4, 5, 7, 5, 4, 6, 4, 6, 4, 1, 5, 5, 8, 8, 5, 3, 1, 1, 4, 7,
       1, 1, 4, 3, 3, 3, 2, 3, 3, 3, 8, 4, 2, 7, 5, 4, 8, 7, 4, 8, 7, 4,
       6, 5, 6, 1, 1, 1, 3, 2, 1, 1, 1, 2, 1, 2, 8, 8, 1, 6, 5, 2, 1, 6,
       7, 8, 3, 1, 6, 2, 6, 6, 2, 7, 2, 3])

In [13]:
np.count_nonzero(rand_arr == 3)

16

In [14]:
unique, counts = np.unique(rand_arr, return_counts=True)

print(np.asarray((unique, counts)).T)

[[ 1 18]
 [ 2 14]
 [ 3 16]
 [ 4 13]
 [ 5  8]
 [ 6 10]
 [ 7  8]
 [ 8 13]]


In [16]:
even_num = (rand_arr % 2 !=1)
rand_arr[even_num] = -1
rand_arr

array([-1,  7, -1, -1,  3,  3, -1,  3, -1, -1,  3,  1, -1, -1, -1,  1, -1,
       -1, -1,  3, -1,  1,  3, -1, -1,  5,  7,  5, -1, -1, -1, -1, -1,  1,
        5,  5, -1, -1,  5,  3,  1,  1, -1,  7,  1,  1, -1,  3,  3,  3, -1,
        3,  3,  3, -1, -1, -1,  7,  5, -1, -1,  7, -1, -1,  7, -1, -1,  5,
       -1,  1,  1,  1,  3, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1, -1,  5,
       -1,  1, -1,  7, -1,  3,  1, -1, -1, -1, -1, -1,  7, -1,  3])

In [24]:
import numpy as np
a = [10,20,30,40,50,60,70,80,90]
b = [23, 39, 51 , 71]

def distance_cal(pf, vari):
     a = np.array(pf)
     b = np.array(vari)
     sum = 0
     for i in range(b.shape[0]):
        valu = np.abs(np.subtract(a,b[i]))
        sum = sum + valu.min()
     print(sum)

distance_cal(a, b)


6


In [13]:
import pandas as pd

dis ={"A":[ np.nan, 1, 2, 3],
      "B" :[5,6,np.nan,8],
      }

df = pd.DataFrame(dis)
df.replace(np.nan, 0)

A    B
0  0.0  5.0
1  1.0  6.0
2  2.0  0.0
3  3.0  8.0

In [33]:
def cal_min_turns(total_num_pages, target_page):
    
    if(total_num_pages % 2==0):
        total_num_pages = total_num_pages+1
        
    front_turn =  (target_page +1) /2
    bact_turn =  (total_num_pages- target_page + 1) /2
    
    return min(front_turn,bact_turn )
print(int(cal_min_turns(99, 95)))
    

2


In [34]:
dic_values = {
    "a":[1,2],
    "b":[3,4],
}
for key, value in dic_values.items():
    print(key, value)

a [1, 2]
b [3, 4]


In [35]:
a =[1,3,4,6,1,2,1]

In [36]:
dub=[]
for value in a:
    num = a.count(value)
    if num > 1:
         if dub.count(value) == 0:
             dub.append(value)
dub           

[1]

In [41]:
b =[1,3,5,7]
Target =10 
# sum of output list should be close to 10

c=[]
for value in b:
    
    
    c.append(abs(Target-value))
    
c
    

[9, 7, 5, 3]

In [44]:
d = ["ash", 1, 2]

for i in d:
    if isinstance(i , str) == true
    #print(i, type(i))

True
False
False


In [46]:
a= [1,2,3,5,4]

len(a)

5

In [50]:
def remove_mid(arr):
    mid_point = int(len(arr)/2)
    #print(arr[ :mid_point-1])
    arr = arr[ :mid_point-1] + arr[mid_point:]
    print(arr)
remove_mid([1,2,3,4])

[1, 3, 4]


In [ ]:
A = [1, 3, 5,6, 10, 40, 0, 44, 41, 2, 4, 50, 59, 7, 47, 60, 42, 53, 100, 99, 70]

given_num = 50

#find 5 nearest values of 50 from the list

fun(list, given_num , k = 5)

#result:

#50, 53, 47,  44, 42

In [10]:
import numpy as np
A = [1, 3, 5,6, 10, 40, 0, 44, 41, 2, 4, 50, 59, 7, 47, 60, 42, 53, 100, 99, 70]

given_num = 50

sorted(A)

def num_nearest(list_A, num):
    list_A = np.asarray(list_A)
    diff =   np.abs(list_A - num)
    arg = np.argsort(diff)
    arg = arg[0:5]
    for i in arg:
       print(list_A[i])
num_nearest(A, given_num )    

50
53
47
44
42


In [10]:
!pip install Pillow
import numpy as np
from PIL import Image
a = np.random.randint(100, size=(100, 100), dtype = np.uint8)
img = Image.fromarray(a)
img.show()


In [14]:
w,h = 11, 11
r = 5
a,b = 5,5

chart = [["*" for x in range(w)] for y in range(h) ]

for y in range(h):
    for x in range(w):
        if abs((x-a)**2 +(y-b)**2-r**2) < 2.2**2:
            chart[y][x] = "&"

for i in chart:
     print(" ".join(i))

* * * & & & & & * * *
* * & * * * * * & * *
* & * * * * * * * & *
& * * * * * * * * * &
& * * * * * * * * * &
& * * * * * * * * * &
& * * * * * * * * * &
& * * * * * * * * * &
* & * * * * * * * & *
* * & * * * * * & * *
* * * & & & & & * * *


In [ ]:
az iot hub invoke-module-method -n IOTQLTDVLGENOBAWE01-iot-hub -d EDQLTDVLGENOBAWE01-qlt-edge-2 -m decision-maker --method-name 'add_team_instruction' --method-payload '{"correlationId": "correlation_id","params": {"version": "latest","mouldId": "b9701u2","bladeRevision": "b97-00","bladeSn": "blade_sn_b9702u2_18","layerId":"090_B97-00_LP_Outer_B1_1-288","palletId": "pallet_2"}}'


In [18]:
str_a = "aaaabbbabcefgh"
dic = { "a":0,"b":0, "c":0,"e":0, "f":0, "g":0,"h":0}

for value in str_a:
    dic[value] +=1    

val=max(dic, key= dic.get)

str_a.split(val)

['', '', '', '', 'bbb', 'bcefgh']

In [69]:
s = "aaabbbccaabb"
output= "3a3b2c2a2b"


# def count_cal(org, key, count, value_count, value):
#     if org == key:
#       #print(count)  
#       print("value is", s[count:value+1], value_count+1, count)
#       count = count+1
#       value_count = value_count+1
    
# count = 0
# key = s[0]
# value_count =0
# for value in range(len(s)):
#     if s[value] == key:
#       #print(count)  
#       print("value is", s[count:value+1], value_count+1, count)
#       count = count+1
#       value_count = value_count+1
    
#     else:
#         value_count = 0
#         key = s[value]  
#         print("key is updated",key)

from collections import Counter
count_str = Counter(s)
current_letter = ""
output = ""
for letter in s:
  if current_letter == letter:
       continue
  else:
    output = output + str(count_str[letter]) + letter
    current_letter = letter
output

'5a5b2c5a5b'

In [35]:
s = 'TCAAAAACCABBBT'
start = 0
for i in range(1, len(s) + 1):
    if (i==len(s) or s[i] != s[i-1]):
        if (i - start > 1):
            print(start, i - start)
        start = i

2 5
7 2
10 3


In [38]:
import re
my_str = "aaabbbccaabb"
[len(z) for z in re.split("y+", my_str)]

[12]

In [40]:
s = "111000222334455555"

from itertools import groupby

groups = groupby(s)
result = [(label, sum(1 for _ in group)) for label, group in groups]
result

[('1', 3), ('0', 3), ('2', 3), ('3', 2), ('4', 2), ('5', 5)]

In [60]:
#Using list comprehensions get values which start with letter "B", ignore case

text = [['bar','foo',6.5],['Boston','Rome',5], ['aa','bb','cc','dd','3']]

#expected output: res = ['bar','Boston','bb']
text

[['bar', 'foo', 6.5], ['Boston', 'Rome', 5], ['aa', 'bb', 'cc', 'dd', '3']]

In [66]:
List_B =[]
for i in text:
    for j in i:
        if type(j) is str and "b"in j.lower() :
        #and j.lower() in "b":
           List_B.append(j)
           print(j)
        #print()
List_B        

bar
Boston
bb


['bar', 'Boston', 'bb']

In [56]:
#Aasshhffaaqq

str_out = []
Input = "Ashfaq"
for i in Input:
    for j in i:
        str_out.append(i)
        str_out.append(j.lower())

print("".join(str_out))

Aasshhffaaqq


In [ ]:

let Source = Json.Document(Web.Contents("https://api.loganalytics.io/v1/workspaces/a05dd03a-d23f-44c6-8297-33f01c9d6c5b/query",
[Query=[#"query"="toolchainLogs_CL
| extend log = parse_json(log_s)
| where log.attrs.tag contains ""edge-detection""
| extend log_json = parse_json(tostring(log.log))
| extend message = log_json.message
| where isnotempty(message)
| extend timestamp = log_json.asctime
| order by TimeGenerated
| take 5000
| extend level = log_json.levelname
| extend location=strcat(log_json.filename, "":"", log_json.lineno)
| project timestamp, level, location, message, server=server_s, log_msg=log_json
",#"x-ms-app"="OmsAnalyticsPBI",#"timespan"="P1D",#"prefer"="ai.response-thinning=true"],Timeout=#duration(0,0,4,0)])),
TypeMap = #table(
{ "AnalyticsTypes", "Type" },
{
{ "string", Text.Type },
{ "int", Int32.Type },
{ "long", Int64.Type },
{ "real", Double.Type },
{ "timespan", Duration.Type },
{ "datetime", DateTimeZone.Type },
{ "bool", Logical.Type },
{ "guid", Text.Type },
{ "dynamic", Text.Type }
}),
DataTable = Source[tables]{0},
Columns = Table.FromRecords(DataTable[columns]),
ColumnsWithType = Table.Join(Columns, {"type"}, TypeMap , {"AnalyticsTypes"}),
Rows = Table.FromRows(DataTable[rows], Columns[name]),
Table = Table.TransformColumnTypes(Rows, Table.ToList(ColumnsWithType, (c) => { c{0}, c{3}}))
in
Table

